namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: string;
    NEXT_PUBLIC_MAPBOX_DIRECTIONS_API_BASE_URL:string;
    NEXT_PUBLIC_ROUTE_CHECK_L1_BASE_URL:string;
    NEXT_PUBLIC_GEODATA_BASE_URL:string;
  }
}